# 元々あるものからアダプタとかを変更。
# デフォルト
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# アプリ開発
development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_rails7_development
  # ↑アプリ名などによって、ここは変わるから気をつけて！

# テスト環境
test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_rails7_test
  # ↑アプリ名などによって、ここは変わるから気をつけて！

# プロダクション（本番）
production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
# 次はジェムファイルロックをターミナル上でする（bundle lock --add-platform x86_64-linux）
# ギットハブからクローンんした場合、秘密情報管理用ファイルがないんため、
# config/credentials.yml.encのファイルを削除すると必要なファイルが自動生成される（ EDITOR="vi" bin/rails credentials:edit）